services:
  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: miappdb
    networks:
      - app-network

  backend:
    build:
      context: ./
      dockerfile: DockerFile
    image: risotto-backend:latest
    container_name: backend-app
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - app-network
    env_file:
      - ./.env  
volumes:
  mongo-data:

networks:
  app-network:
    external: true
